# Generated by Django 4.1.5 on 2023-01-19 18:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='workerModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=200)),
                ('adscripcion', models.CharField(max_length=200)),
                ('turno', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('createdat', models.DateTimeField(default=datetime.datetime(2023, 1, 19, 18, 23, 16, 962678))),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugueteapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='childModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('f_nac', models.CharField(max_length=200)),
                ('edad', models.FloatField()),
                ('sexo', models.CharField(max_length=20)),
                ('entregado', models.CharField(blank=True, max_length=100, null=True)),
                ('createdat', models.DateTimeField(default=datetime.datetime(2023, 1, 19, 18, 23, 16, 963054))),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugueteapp.workermodel')),
            ],
        ),
    ]
