# Generated by Django 5.1.7 on 2025-03-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugueteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workermodel',
            name='edad',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='workermodel',
            name='sexo',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='createdat',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='f_nac',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='workermodel',
            name='createdat',
            field=models.DateTimeField(),
        ),
    ]
