# Generated by Django 4.1.5 on 2023-01-20 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugueteapp', '0002_alter_childmodel_createdat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workermodel',
            name='antiguedad',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workermodel',
            name='domicilio',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='workermodel',
            name='t_contr',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workermodel',
            name='telefono',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='childmodel',
            name='createdat',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 20, 17, 30, 13, 389028)),
        ),
        migrations.AlterField(
            model_name='workermodel',
            name='createdat',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 20, 17, 30, 13, 389028)),
        ),
    ]
