# Generated by Django 4.1.5 on 2023-01-24 20:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='workerModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=200)),
                ('antiguedad', models.CharField(max_length=30, null=True)),
                ('adscripcion', models.CharField(max_length=200)),
                ('t_contr', models.CharField(max_length=30, null=True)),
                ('turno', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('domicilio', models.CharField(max_length=250, null=True)),
                ('telefono', models.CharField(max_length=30, null=True)),
                ('createdat', models.DateTimeField(default=datetime.datetime(2023, 1, 24, 14, 25, 49, 960197))),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'worker',
            },
        ),
        migrations.CreateModel(
            name='childModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('f_nac', models.CharField(max_length=200)),
                ('edad', models.FloatField()),
                ('sexo', models.CharField(max_length=20)),
                ('entregado', models.CharField(blank=True, max_length=100, null=True)),
                ('createdat', models.DateTimeField(default=datetime.datetime(2023, 1, 24, 14, 25, 49, 961197))),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugueteapp.workermodel')),
            ],
            options={
                'db_table': 'chailds',
            },
        ),
    ]
