from django import forms
from django.core import validators
from django.core.exceptions import ValidationError
from .models import User, workerModel, childModel

class UserForm(forms.Form):
    error_css_class = 'error'
    required_css_class = 'required'
    username = forms.CharField(label='Usuario', max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label='Email', max_length=150, widget=forms.EmailInput(attrs={'class': 'form-control' }))
    password = forms.CharField(label='Password', max_length=150, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
     
    
class loginForm(forms.Form):
    username= forms.EmailField(label='Usuario', max_length=150, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Password', max_length=150, widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class workerForm(forms.Form):

    TURNO = [
        ('MATUTINO', 'MATUTINO'),
        ('VESPERTINO', 'VESPERTINO'),
        ('NOCTURNO', 'NOCTURNO'),
        ('JORNADA ACUMULADA', 'JORNADA ACUMULADA'),
    ]

    T_CONTR = [
        ('02 BASE', '02 BASE'),
        ('03 TEMPORAL', '03 TEMPORAL'),
        ('08 EVENTUAL', '08 EVENTUAL'),
        ('CONFIANZA B', 'CONFIANZA B'),
    ]

    ADSCRIPCIONES = [
	('BANCO DE SANGRE','BANCO DE SANGRE'),
	('CAO','CAO'),
	('CENTRAL DE SERVICIOS','CENTRAL DE SERVICIOS'),
	('CENTRO DE CANJE','CENTRO DE CANJE'),
	('CENTOR DE SIMULACION','CENTRO DE SIMULACION'),
	('CIBO','CIBO'),
	('CLINICA DE MAMA','CLINICA DE MAMA'),
	('DELEGACION JALISCO','DELEGACION JALISCO'),
	('HOSPITAL DE ESPECIALIDADES','HOSPITAL ESPECIALIDADES'),
	('HOSPITAL DE GINECO-OBSTETRICIA','HOSPITAL GINECO-OBSTETRICIA'),
	('HOSPITAL DE PEDIATRIA','HOSPITAL PEDIATRIA'),
	('PATOLOGIA CLINICA','PATOLOGIA CLINICA'),
	('PLANTA CENTRAL DE LAVADO','PLANTA CENTRAL DE LAVADO'),
	('TELECOMUNICACIONES','TELECOMUNICACIONES'),
	('TIENDA CENTRO MEDICO','TIENDA CENTRO MEDICO'),
	('TRANSPORTES','TRANSPORTES'),
	('UMF 003','UMF 003'),
	('HGZ 014','HGZ 014'),
	('UMF 049','UMF 049'),
	('UMF 052','UMF 052'),
	('UMF 054','UMF 054'),
	('UMF 078','UMF 078'),
	('UMF 093','UMF 093'),
	('UMF 167','UMF 167'),
	('UMF 184','UMF 184'),
	('CENTRO COMUNITARIO DE SALUD MENTAL','CENTRO COMUNITARIO DE SALUD MENTAL'),
	('HGR 045','HGR 045'),
	('HOSPITAL JUAN I. MENCHACA','HOSPITAL JUAN I. MENCHACA'),
	('LARRE','LARRE'),
	('UMF 002','UMF 002'),
	('UMF 004','UMF 004'),
	('UMF 008','UMF 008'),
	('UMF 051','UMF 051'),
	('UMF 053','UMF 053'),
	('UMF 079','UMF 079'),
	('UMF 182','UMF 182'),
	('ALMACEN DELEGACIONAL','ALMACEN DELEGACIONAL'),
	('CENTOR DE SEGURIDAD SOCIAL GUADALAJARA','CENTRO DE SEGURIDAD SOCIAL GUADALAJARA'),
	('HGR 046','HGR 046'),
	('TIENDA CAMPESINO','TIENDA CAMPESINO'),
	('UMF 001','UMF 001'),
	('UMF 034','UMF 034'),
	('UMF 039','UMF 039'),
	('UMF 088','UMF 088'),
	('UMF 091','UMF 091'),
	('UMF 092','UMF 092'),
	('HGZ 089','HGZ 089'),
	('UMF 055','UMF 055'),
	('UMF 171','UMF 171'),
	('UMF 178','UMF 178'),
	('VELATORIO','VELATORIO'),
	('HGR 110','HGR 110'),
	('UMF 048','UMF 048'),
	('HGR 180','HGR 180'),
	('UMF 059','UMF 059'),
	('CENTRO DE CAPACITACION Y CALIDAD JALISCO','CENTRO DE CAPACITACION Y CALIDAD JALISCO'),
	('GUARDERIA 01','GUARDERIA 01'),
	('GUARDERIA 02','GUARDERIA 02'),
	('GUARDERIA 03','GUARDERIA 03'),
	('GUARDERIA 04','GUARDERIA 04'),
	('GUARDERIA 05','GUARDERIA 05'),
	('SUBDELEGACION REFORMA LIBERTAD','SUBDELEGACION REFORMA LIBERTAD'),
	('SUBDELEGACION JUAREZ','SUBDELEGACION JUAREZ'),
	('SUBDELEGACION HIDALGO','SUBDELEGACION HIDALGO'),
	('ESCUELA DE ENFERMERIA','ESCUELA DE ENFERMERIA'),
	('HGZ 020 AUTLAN DE NAVARRO','HGZ 020 AUTLAN DE NAVARRO'),
	('PUESTO DE ENFERMERIA 125 EL LIMON','PUESTO DE ENFERMERIA 125 EL LIMON'),
	('PUESTO DE ENFERMERIA 127 TONAYA','PUESTO DE ENFERMERIA 127 TONAYA'),
	('UMF 071 AYUTLA','UMF 071 AYUTLA'),
	('UMF 081 EL GRULLO','UMF 081 EL GRULLO'),
	('HGsZ 028 CASIMIRO CASTILLO','HGsZ 028 CASIMIRO CASTILLO'),
	('PUESTO DE ENFERMERIA 122 CUATITLAN','PUESTO DE ENFERMERIA 122 CUATITLAN'),
	('UMF 070 CAREYES','UMF 070 CAREYES'),
	('UMF 080 CIHUATLAN','UMF 080 CIHUATLAN'),
	('UMF 083 LA HUERTA','UMF 083 LA HUERTA'),
	('UMF 162 MELAQUE','UMF 162 MELAQUE'),
	('CENTRO DE SEGURIDAD SOCIAL CD. GUZMAN','CENTRO DE SEGURIDAD SOCIAL CD. GUZMAN'),
	('HGsZ 015 TAMAZULA','HGsZ 015 TAMAZULA'),
	('HGZ 009 CD. GUZMAN','HGZ 009 CD. GUZMAN'),
	('OFNA AUX 120','OFNA AUX 120'),
	('OFNA AUX 150','OFNA AUX 150'),
	('PUESTO DE ENFERMERIA 180 TOLIMAN','PUESTO ENFERMERIA 180 TOLIMAN'),
	('SUBDELEGACION CD. GUZMAN','SUBDELEGACION CD. GUZMAN'),
	('TIENDA CD. GUZMAN','TIENDA CD. GUZMAN'),
	('UMF 013 PIHUAMO','UMF 013 PIHUAMO'),
	('UMF 016 TECALITLAN','UMF 016 TECALITLAN'),
	('UMF 017 ATENQUIQUE','UMF 017 ATENQUIQUE'),
	('UMF 018 ZAPOTILTIC','UMF 018 ZAPOTILTIC'),
	('UMF 019 TUXPAN','UMF 019 TUXPAN'),
	('UMF 033 SAN MARCOS','UMF 033 SAN MARCOS'),
	('UMF 035 VISTA HERMOSA','UMF 035 VISTA HERMOSA'),
	('UMF 036 LA GARITA','UMF 036 LA GARITA'),
	('UMF 061 MAZAMITLA','UMF 061 MAZAMITLA'),
	('UMF 062 SAYULA','UMF 062 SAYULA'),
	('UMF 063 SAN GABRIEL','UMF 063 SAN GABRIEL'),
	('UMF 064 TAPALPA','UMF 064 TAPALPA'),
	('UMF 065 TECHALUTA','UMF 065 TECHALUTA'),
	('UMF 076 TEOCUITATLAN','UMF 076 TEOCUITATLAN'),
	('UMF 114 GOMEZ FARIAS','UMF 114 GOMEZ FARIAS'),
	('PUESTO DE ENFERMERIA 155 TIZAPAN','PUESTO DE ENFERMERIA 155 TIZAPAN'),
	('UMF 005 EL SALTO','UMF 005 EL SALTO'),
	('UMF 040 CHAPALA','UMF 040 CHAPALA'),
	('UMF 047 ZAPOTLANEJO','UMF 047 ZAPOTLANEJO'),
	('UMF 057 IXTLAHUCAN DEL RIO','UMF 057 iXTLAHUACAN DEL RIO'),
	('UMF 058 JOCOTEPEC','UMF 058 JOCOTEPEC'),
	('UMF 060 COLOTLAN','UMF 060 COLOTLAN'),
	('UMF 068 BOLAÑOS','UMF 068 BOLAÑOS'),
	('UMF 106 SAN MARTIN DE BOLAÑOS','UMF 106 SAN MARTIN BOLAÑOS'),
	('UMF 181 IXTLAHUACAN DE LOS MEMBRILLOS','UMF 181 IXTLAHUACAN DE LOS MEMBRILLOS'),
	('CENTRO DE SEGURIDAD LAGOS DE MORENO','CENTRO DE SEGURIDAD LAGOS DE MORENO'),
	('HGZ 007 LAGOS DE MORENO','HGZ 007 LAGOS DE MORENO'),
	('PUESTO DE ENFERMERIA 130 OJUELOS','PUESTO DE ENFERMERIA 130 OJUELOS'),
	('PUESTO DE ENFERMERIA 133 UNION DE SAN ANTONIO','PUESTO DE ENFERMERIA 133 UNION DE SAN ANTONIO'),
	('PUESTO DE ENFERMERIA 135 VILLA HIDALGO','PUESTO DE ENFERMERIA 135 VILLA HIDALGO'),
	('SUBDELEGACION LAGOS DE MORENO','SUBDELEGACION LAGOS DE MORENO'),
	('UMF 041 SAN JUAN DE LOS LAGOS','UMF 041 SAN JUAN DE LOS LAGOS'),
	('UMF 084 ENCARNACION DE DIAZ','UMF 084 ENCARNACION DE DIAZ'),
	('UMF 087 TEOCALTIOCHE','UMF 087 TEOCALTICHE'),
	('UMF 131 SAN DIEGO DE ALEJANDRIA','UMF 131 SAN DIEGO DE ALEJANDRIA'),
	('UMF 177 LAGOS DE MORENO','UMF 177 LAGOS DE MORENO'),
	('CENTRO DE SEGURIDAD SOCIAL OCOTLAN','CENTRO DE SEGURIDAD SOCIAL OCOTLAN'),
	('HGZ 006 OCOTLAN','HGZ 006 OCOTLAN'),
	('SUBDELEGACION OCOTLAN','SUBDELEGACION OCOTLAN'),
	('UMF 022 ATOTONILCO','UMF 022 ATOTONILCO'),
	('UMF 023 LA BARCA','UMF 023 LA BARCA'),
	('UMF 050 ATOTONILQUILLO','UMF 050 ATOTONILQUILLO'),
	('UMF 066 AYOTLAN','UMF 066 AYOTLAN'),
	('UMF 067 TOTOTLAN','UMF 067 TOTOTLAN'),
	('UMF 095 PONCITLAN','UMF 095 PONCITLAN'),
	('UMF 100 JAMAY','UMF 100 JAMAY'),
	('UMF 165 DEGOLLADO','UMF 165 DEGOLLADO'),
	('UMF 169 OCOTLAN','UMF 169 OCOTLAN'),
	('HGZ 042 PUERTO VALLARTA','HGZ 042 PUERTO VALLARTA'),
	('SUBDELEGACION PUERTO VALLARTA','SUBDELEGACION PUERTO VALLARTA'),
	('UMF 043 TOMATLAN','UMF 043 TOMATLAN'),
	('UMF 170 PUERTO VALLARTA','UMF 170 PUERTO VALLARTA'),
	('UMF 179 PUERTO VALLARTA','UMF 179 PUERTO VALLARTA'),
	('HGZ 026 TALA','HGZ 026 TALA'),
	('OFNA AUX 139 GUACHINANGO','OFNA AUX 139 GUACHINANGO'),
	('OFNA AUX 142 MIXTLAN','OFNA AUX 142 MIXTLAN'),
	('OFNA AUX 143 SAN MARCOS','OFNA AUX 143 SAN MARCOS'),
	('OFNA AUX TALA','OFNA AUX TALA'),
	('PUESTO ENFERMERIA 144 SAN SEBASTIAN DEL OESTE','PUESTO ENFERMERIA 144 SAN SEBASTIAN DEL OESTE'),
	('PUESTO DE ENFERMERIA HOSTOTIPAQUILLO','PUESTO DE ENFERMERIA HOSTOTIPAQUILLO'),
	('UMF 010 TEQUILA','UMF 010 TEQUILA'),
	('UMF 011 AMATITAN','UMF 011 AMATITAN'),
	('UMF 012 ARENAL','UMF 012 ARENAL'),
	('UMF 024 AMECA','UMF 024 AMECA'),
	('UMF 031 AHUALULCO DEL MERCADO','UMF 031 AHUALULCO DEL MERCADO'),
	('UMF 038 BUENAVISTA','UMF 038 BUENAVISTA'),
	('UMF 069 ETZATLAN','UMF 069 ETZATLAN'),
	('UMF 074 TALPA DE ALLENDE','UMF 074 TALPA DE ALLENDE'),
	('UMF 096 MASCOTA','UMF 096 MASCOTA'),
	('UMF 097 MAGDALENA','UMF 097 MAGDALENA'),
	('UMF 098 TEUCHITLAN','UMF 098 TEUCHITLAN'),
	('UMF 137 SAN JUANITO ESCOBEDO','UMF 137 SAN JUANITO ESCOBEDO'),
	('HGZ 021 TEPATITLAN DE MORELOS','HGZ 021 TEPATITLAN DE MORELOS'),
	('PUESTO DE ENFERMERIA 132 SAN JUAN','PUESTO DE ENFERMERIA 132 SAN JUAN'),
	('PUESTO DE ENFERMERIA 134 VALLE DE GUADALUPE','PUESTO DE ENFERMERIA 134 VALLE DE GUADALUPE'),
	('PUESTO DE ENFERMERIA 136 CAÑADAS DE OBREGON','PUESTO DE ENFERMERIA 136 CAÑADAS DE OBREGON'),
	('SUBDELEGACION TEPATITLAN DE MORELOS','SUBDELEGACION TEPATITLAN DE MORELOS'),
	('UMF 044 ARANDAS','UMF 044 ARANDAS'),
	('UMF 085 JALOSTOTITLAN','UMF 085 JALOSTOTITLAN'),
	('UMF 094 YAHUALICA','UMF 094 YAHUALICA'),
	('UMF 128 ACATIC','UMF 128 ACATIC'),
	('UMF 159 JESUS MARIA','UMF 159 JESUS MARIA'),
	('UMF 160 CAPILLA DE GUADALUPE','UMF 160 CAPILLA DE GUADALUPE'),
	('UMF 168 TEPATITLAN DE MORELOS','UMF 168 TEPATITLAN DE MORELOS'),
	('UMF 183 SAN IGNACIO CERRO GORDO','UMF 183 SAN IGNACIO CERRO GORDO'),
	('HGsZ 027 VILLA CORONA','HGsZ 027 VILLA CORONA'),
	('OFNA AUX 147 ATEMAJAC DE BRIZUELA','OFNA AUX 147 ATEMAJAC DE BRIZUELA'),
	('PUESTO DE ENFERMERIA 152 JUCHITLAN','PUESTO DE ENFERMERIA 152 JUCHITLAN'),
	('PUESTO DE ENFERMERIA 154 TENAMAXTLAN','PUESTO DE ENFERMERIA 154 TENAMAXTLAN'),
	('UMF 025 LA SAUCEDA','UMF 025 LA SAUCEDA'),
	('UMF 029 ESTIPAC','UMF 029 ESTIPAC'),
	('UMF 030 BELLAVISTA','UMF 030 BELLAVISTA'),
	('UMF 056 ACATLAN DE JUAREZ','UMF 056 ACATLAN DE JUAREZ'),
	('UMF 072 COCULA','UMF 072 COCULA'),
	('UMF 073 SAN MARTIN HIDALGO','UMF 073 SAN MARTIN HIDALGO'),
	('UMF 075 TECOLOTLAN','UMF 075 TECOLOTLAN'),
	('UMF 077 ZACOALCO DE TORRES','UMF 077 ZACOALCO DE TORRES'), ]

    CATEGORIAS = [
("Pasante de Abogado", "Pasante de Abogado"), ("Aboado", "Abogado"),
("AAuxiliar Técnico de Actuariado Social", "Auxiliar Técnico de Actuariado Social"),
("Oficial Técnico de Actuariado Social", "Oficial Técnico de Actuariado Social"), 
("Técnico de Actuariado Social", "Técnico de Actuariado Social"), 
("Actuario Social Matemático", "Actuario Social Matemático"), 
("Auxilia de Almacen", "Auxiliar de Almacen"), 
("Oficial de Almacen","Oficial de Almacén"), 
("Coordinador de Alamacén","Coordinador de Almacén"),
("Jefe de Grupo de Almacén","Jefe de Grupo de Almacén"),
("Especialista de Almacén","Especialista de Almacén"),
("Arquitecto","Arquitecto"),
("Asistente Médica","Asistente Medica"), 
("Coordinadora de Asistente Médica", "Coordinadora de Asistente Medica"), 
("Ayudante de Autopsias","Ayudante de Autopsias"), 
("Auxiliar de Servicios Administrativos","Auxiliar de Servicios Administrativos"),
("Técnico de Bibliotecas","Tecnico de Bibliotecas"), 
("Asistente de Bibliotecario","Asistente de Bibliotecario"), 
("Bibliotecario", "Bibliotecario"), 
("Técnico de Bibliotecas","Tecnico de Bibliotecas"), 
("Asistente de Bibliotecario","Asistente de Bibliotecario"), 
("Ayudante de Cajero B","Ayudante de Cajero B"), 
("Ayudante de Cajero A","Ayudante de Cajero A"), 
("Cajero D","Cajero D"), ("","Cajero C"), ("","Cajero B"), ("","Cajero A"), 
("Camillero de Unidades Medicas","Camillero de Unidades Medicas"), 
("Auxiliar de Administracion de C.V.", "Auxiliar de Administracion de C.V."), 
("Auxiliar de Atencion Medica ccd C.V.", "Auxiliar de Atencion Medica ccd C.V."), 
("Auxiliar de Hospedaje de C.V.", "Auxiliar de Hospedaje de C.V."), 
("Auxiliar de Operacion Contable de C.V.", "Auxiliar de Operacion Contable de C.V."), 
("Lavandero en Centros Vacacionales","Lavandero en Centros Vacacionales"), 
("Operador de Seguridad en Albercas de C.V.","Operador de Seguridad en Albercas de C.V."), 
("Operador de Servicios Internos de C.V.","Operador de Servicios Internos de C.V."), 
("Operador de Vehiculos de C.V.","Operador de Vehiculos de C.V."), 
("Planchador de Centros Vacacionales","Planchador de Centros Vacacionales"), 
("Vigilante de Centros Vacacionales","Vigilante de Centros Vacacionales"), 
("Cirujano Maxilo Facal","Cirujano Maxilo Facal"), 
("Citotecnologo","Citotecnologo"), 
("Tecnico Polivalente","Tecnico Polivalente"),
("Tecnico Electrisista","Tecnico Electrisista"), 
("Tecnico Electronico","Tecnico Electronico"),
("Tecnico Mecanico","Tecnico Mecanico"),
("Tecnico Plomero","Tecnico Plomero"),
("Tecnico A en Aire Acondicionado y Refrigeracion","Tecnico A en Aire Acondicionado y Refrigeracion"), 
("Tecnico A en Equipos Medicos","Tecnico A en Equipos Medicos"),
("Tecnico A en Fluidos y Energeticos","Tecnico A en Fluidos y Energeticos"),
("Tecnico A en Plantas de Lavado","Tecnico A en Plantas de Lavado"),
("Tecnico A en Telecomunicaciones","Tecnico A en Telecomunicaciones"),
("Tecnico B en Equipos Medicos","Tecnico B en Equipos Medicos"),
("Tecnico B en Fluidos y Energeticos","Tecnico B en Fluidos y Energeticos"),
("Tecnico B en Planta de Lavado","Tecnico B en Planta de Lavado"),
("Tecnico B en Telecomunicaciones","Tecnico B en Telecomunicaciones"),
("Tecnico en Equipos Reciprocantes","Tecnico en Equipos Reciprocantes"),
("Tecnico en Electronica Medica y Laboratorio","Tecnico en Electronica Medica y Laboratorio"),
("Tecnico C en Fluidos y Energeticos","Tecnico C en Fluidos y Energeticos"),
("Tecnico C en Plantas de Lavado","Tecnico C en Plantas de Lavado"),
("Tecnico C en Telecomunicaciones","Tecnico C en Telecomunicaciones"),
("Tecnico en Mecanica, Fluidos y Especialidades","Tecnico en Mecanica, Fluidos y Especialidades"),
("Tecnico en Equipos de Absorcion","Tecnico en Equipos de Absorcion"),
("Tecnico en Equipos Helicoidal","Tecnico en Equipos Helicoidal"),
("Tecnico en Equipo de Rayos X","Tecnico en Equipo de Rayos X"),
("Tecnico en Equipos Turbocentrifugo","Tecnico en Equipos Turbocentrifugo"),
("Especialista en Equipo de Especialidades","Especialista en Equipo de Especialidades"),
("Especialista en Equipos de Laboratorio","Especialista en Equipos de Laboratorio"),
("Especialista en Equipos de Medica y Fluidos","Especialista en Equipos de Medica y Fluidos"),
("Especialista en Equipos de Aire Acondicionado y Refrigeracion","Especialista en Equipos de Aire Acondicionado y Refrigeracion"),
("Especialista en Plantas de Lavado","Especialista en Plantas de Lavado"),
("Especialista en Equipos de Electronica Medica","Especialista en Equipos de Electronica Medica"),
("Especialista en Equipos de Rayos X","Especialista en Equipos de Rayos X"),
("Especialista en Fluidos y Energeticos","Especialista en Fluidos y Energeticos"), 
("Contador","Contador"), 
("Contador Auditor","Contador Auditor"),
("Cuidador de Animales","Cuidador de Animales"), 
("Dibujante de Construccion","Dibujante de Construccion"), 
("Dibujante de Estadistica y Publicidad C","Dibujante de Estadistica y Publicidad C"),
("Dibujante de Estadistica y Publicidad B","Dibujante de Estadistica y Publicidad B"),
("Dibujante de Estadistica y Publicidad A","Dibujante de Estadistica y Publicidad A"),
("Dibujante de Ingenieria y Arquitectura","Dibujante de Ingenieria y Arquitectura"), 
("Pasante de Economista","Pasante de Economista"), 
("Economista","Economista"), 
("Educadora","Educadora"),
("Electrocardiografista","Electrocardiografista"), 
("Elevadorista","Elevadorista"), 
("Auxiliar de Enfermeria General","Auxiliar de Enfermeria General"),
("Auxiliar de Enfermeria en Salud Publica","Auxiliar de Enfermeria en Salud Publica"),
("Enfermera General","Enfermera General"),
("Enfermera Especialista","Enfermera Especialista"),
("Enfermera Jefe de Piso","Enfermera Jefe de Piso"), 
("Estomatologo","Estomatologo"), 
("Auxiliar de Farmacia","Auxiliar de Farmacia"), 
("Ayudante de Farmacia","Ayudante de Farmacia"), 
("Oficila de Farmacia","Oficial de Farmacia"), 
("Coordinador de Farmacia","Coordinador de Farmacia"), 
("Fonoaudiologo","Fonoaudiologo"), 
("Guardavisas","Guardavidas"), 
("Oficial de Puericultura","Oficial de Puericultura"), 
("Tecnico de Puericultura","Tecnico de Puericultura"), 
("Heliografista","Heliografista"), 
("Histotecnologo","Histotecnologo"), 
("Pasante de Ingeniero","Pasante de Ingeniero"), 
("Ingeniero","Ingeniero"), 
("Inhaloterapia","Inhaloterapia"), 
("Auxiliar de Servicios de Intendencia","Auxiliar de Servicios de Intendencia"), 
("Ayudante de Servicios de Intendencia","Ayudante de Servicios de Intendencia"), 
("Oficial Servicio de Intendencia","Oficial Servicio de Intendencia"), 
("Intendente","Intendente"), 
("Auxiliar de Laboratorio","Auxiliar de Laboratorio"),
("Laboratorista","Laboratorista"),
("Operador de Servicios de Lavanderia","Operador de Servicios de Lavanderia"), 
("Oficial de Servicios de Lavanderia","Oficial de Servicios de Lavanderia"), 
("Auxiliar de Limpieza e Higiene en Unidades Medicas y No Medicas","Auxiliar de Limpieza e Higiene en Unidades Medicas y No Medicas"), 
("Ayudante de Limpieza e Higiene en Unidades Medicas y No Medicas","Ayudante de Limpieza e Higiene en Unidades Medicas y No Medicas"), 
("Machetero","Machetero"), 
("Masajista","Masajista"), 
("Medico General","Medico General"), 
("Medico No Familiar","Medico No Familiar"), 
("Medico Familiar","Medico Familiar"),
("Tecnico de Microfotografia","Tecnico de Microfotografia"),  
("Multilitista","Multilitista"), 
("Nutricion Dietista","Nutricion Dietista"), 
("Especialista en Nutricion y Dietetica","Especialista en Nutricion y Dietetica"), 
("Nutriologo Clinico Especializado","Nutriologo Clinico Especializado"),
("Operador de Maquinas de Revelado Automatico","Operador de Maquinas de Revelado Automatico"),
("Optometrista","Optometrista"), 
("Orientador","Orientador"), 
("Orientadoe de Actividades Familiares","Orientadoe de Actividades Familiares"), 
("Orientador de Actividades Artisticas","Orientador de Actividades Artisticas"), 
("Orientador de Actividades Artisticas Danza Regional","Orientador de Actividades Artisticas Danza Regional"), 
("Orientador de Actividades Artisticas Maestro de Musical","Orientador de Actividades Artisticas Maestro de Musical"), 
("Orientador de Actividades Artisticas Arte Dramatico","Orientador de Actividades Artisticas Arte Dramatico"), 
("Orientador de Educacion Fisica","Orientador de Educacion Fisica"),
("Orientador de Iniciacion Cultural","Orientador de Iniciacion Cultural"), 
("Orientador Tecnico Medico","Orientador Tecnico Medico"),                
("Auxiliar de Orientador Tecnico Medico","Auxiliar de Orientador Tecnico Medico"), 
("Ortopedista","Ortopedista"), 
("Partera","Partera"), 
("Jefe de Parteras","Jefe de Parteras"), 
("Peluquero","Peluquero"), 
("Pianista","Pianista"),
("Auxiliar de Administracion en Unidad Medica","Auxiliar de Administracion en Unidad Medica"),
("Auxiliar de Enfermeria en Unidad Medica","Auxiliar de Enfermeria en Unidad Medica"), 
("Auxiliar de Limpieza y Cocina en Unidad Medica","Auxiliar de Limpieza y Cocina en Unidad Medica"), 
("Auxiliar de Servicios Generales en Unidad Medica","Auxiliar de Servicios Generales en Unidad Medica"), 
("Profesor de Educacion Fisica A","Profesor de Educacion Fisica A"), 
("Profesor de Educacion Fisica B","Profesor de Educacion Fisica B"), 
("Profesor de Educacion Fisica C","Profesor de Educacion Fisica C"),
("Promotor de Estomatologia","Promotor de Estomatologia"), 
("Promotor de Salud Comunitaria","Promotor de Salud Comunitaria"), 
("Psicologo","Psicologo"), 
("Psicolog Clinico","Psicolog Clinico"), 
("Psicometra","Psicometra"), 
("Quimico Clinico","Quimico Clinico"), 
("Quimico Clinico Jefe de Seccion","Quimico Clinico Jefe de Seccion"), 
("Tecnico Radiologo","Tecnico Radiologo"), 
("Radioterapeuta","Radioterapeuta"), 
("Redactor B","Redactor B"),
("Auxiliar de Administracion en Unidad Medica","Auxiliar de Administracion en Unidad Medica"), 
("Auxiliar de Enfermeria en Unidad Medica","Auxiliar de Enfermeria en Unidad Medica"), 
("Auxiliar de Limpieza y Cocina en Unidad Medica","Auxiliar de Limpieza y Cocina en Unidad Medica"),
("Auxiliar de Servicios Generales en Unidad Medica","Auxiliar de Servicios Generales en Unidad Medica"),
("Sociologo","Sociologo"), 
("Auxiliar de Soporte Tecnico en Informatica","Auxiliar de Soporte Tecnico en Informatica"), 
("Oficial Soporte Tecnico en Informatica","Oficial Soporte Tecnico en Informatica"), 
("Coordinador de Soporte Tecnico en Informatica","Coordinador de Soporte Tecnico en Informatica"),
("Tecnico en Anestesia","Tecnico en Anestesia"), 
("Tecnico en el manejo de Aparatos de Electrodiagnostico","Tecnico en el manejo de Aparatos de Electrodiagnostico"), 
("Tecnico en Medicina Nuclear","Tecnico en Medicina Nuclear"), 
("Auxiliar de Tecnico en Servicios de Dietologia","Auxiliar de Tecnico en Servicios de Dietologia"),
("Operador Telefonico A","Operador Telefonico A"), 
("Operador Telefonico B","Operador Telefonico B"), 
("Operador Telefonico C","Operador Telefonico C"), 
("Coordinador de Operadores Telefonicos","Coordinador de Operadores Telefonicos"), 
("Terapista Fisico","Terapista Fisico"), 
("Terapista Ocupacional","Terapista Ocupacional"),
("Operador General de Tiendas","Operador General de Tiendas"), 
("Jefe de Linea en Tiendas","Jefe de Linea en Tiendas"), 
("Trabajador Social","Trabajador Social"), 
("Trabajador Social Clinico","Trabajador Social Clinico"), 
("Auxiliar de Trabajo Social","Auxiliar de Trabajo Social"),
("Chofer","Chofer"), 
("Motociclista","Motociclista"), 
("Controlador de Vehiculos","Controlador de Vehiculos"), 
("Enfermera para el Traslado de Pacientes de Urgencia","Enfermera para el Traslado de Pacientes de Urgencia"), 
("Enfermera para el Traslado de Pacientes de Terapia Intensiva","Enfermera para el Traslado de Pacientes de Terapia Intensiva"),
("Tecnico Operador de Transporte de Pacientes de Urgencia","Tecnico Operador de Transporte de Pacientes de Urgencia"),
("Tecnico Operador de Transporte de Pacientes de Terapia Intensiva","Tecnico Operador de Transporte de Pacientes de Terapia Intensiva"),
("Medico para el Traslado de Pacientes de Urgencia","Medico para el Traslado de Pacientes de Urgencia"),
("Medico para el Traslado de Pacientes de Terapia Intensiva","Medico para el Traslado de Pacientes de Terapia Intensiva"), 
("Auxiliar de Administracion en Unidad Medica de Esquema Modificado y Campo","Auxiliar de Administracion en Unidad Medica de Esquema Modificado y Campo"),
("Auxiliar de Atencion Medica en Unidad Medica de Esquema Modificado","Auxiliar de Atencion Medica en Unidad Medica de Esquema Modificado"),
("Auxiliar de Laboratorio en Unidad Medica de Esquema Modificado y Campo","Auxiliar de Laboratorio en Unidad Medica de Esquema Modificado y Campo"),
("Auxiliar de Servicios Generales en Unidad Medica de Esquema Modificado y Campo","Auxiliar de Servicios Generales en Unidad Medica de Esquema Modificado y Campo"), 
("Estomatologo en Unidad Medica de Esquema Modificado y Campo","Estomatologo en Unidad Medica de Esquema Modificado y Campo"),
("Operador de Servicios de Radiodiagnostico en Unidad Medica de Esquema Modificado y Campo","Operador de Servicios de Radiodiagnostico en Unidad Medica de Esquema Modificado y Campo"), 
("Auxiliar de Administracion en Unidad Medica de Esquema Modificado de Campo","Auxiliar de Administracion en Unidad Medica de Esquema Modificado de Campo"),
("Auxiliar de Area Medica en Unidad Medica de Campo","Auxiliar de Area Medica en Unidad Medica de Campo"),
("Auxiliar de Servicios Generales en Unidad Medica de Campo","Auxiliar de Servicios Generales en Unidad Medica de Campo"), 
("Estomatologo en Unidad Medica de Campo Campo","Estomatologo en Unidad Medica de Campo Campo"),
("Operador de Mantenimiento en Unidad Medica de Campo","Operador de Mantenimiento en Unidad Medica de Campo"), 
("Operador de Servicios Auxiliares en Unidad Medica de Campo laboratorio","Operador de Servicios Auxiliares en Unidad Medica de Campo laboratorio"), 
("Operador de Servicios Auxiliares en Unidad Medica de Campo Radiodiagnostico","Operador de Servicios Auxiliares en Unidad Medica de Campo Radiodiagnostico"), 
("Mensajero","Mensajero"), 
("Auxiliar Universal de Oficinas","Auxiliar Universal de Oficinas"), 
("Oficial de Tesoreria","Oficial de Tesoreria"), 
("Coordinador de Tesoreria","Coordinador de Tesoreria"), 
("Jefe de Grupo de Tesoreria","Jefe de Grupo de Tesoreria"), 
("Especialista de Tesoreria","Especialista de Tesoreria"),
("Oficial de Servicios Tecnicos","Oficial de Servicios Tecnicos"),
("Coordinador de Servicios Tecnicos","Coordinador de Servicios Tecnicos"),
("Jefe de Grupo de Servicios Tecnicos","Jefe de Grupo de Servicios Tecnicos"),
("Especialista de Servicios Tecnicos","Especialista de Servicios Tecnicos"),
("Oficial de Servicios Administrativos","Oficial de Servicios Administrativos"),
("Coordinador de Servicios Administrativos","Coordinador de Servicios Administrativos"),
("Jefe de Grupo de Servicios Administrativos","Jefe de Grupo de Servicios Administrativos"),
("Especialista de Servicios Administrativos","Especialista de Servicios Administrativos"),
("Oficial de Personal","Oficial de Personal"),
("Coordinador de Personal","Coordinador de Personal"),
("Jefe de Grupo de Personal","Jefe de Grupo de Personal"),
("Especialista de Personal","Especialista de Personal"),
("Oficial de Estadistica","Oficial de Estadistica"),
("Coordinador de Estadistica","Coordinador de Estadistica"),
("Jefe de Grupo Estadistica","Jefe de Grupo Estadistica"),
("Especialista de Estadistica","Especialista de Estadistica"),
("Oficial de Procesameinto de Datos","Oficial de Procesameinto de Datos"),
("Coordinador de Procesamiento de Datos","Coordinador de Procesamiento de Datos"),
("Jefe de Grupo de Procesamiento de Datos","Jefe de Grupo de Procesamiento de Datos"),
("Especialista de Procesamiento de Datos","Especialista de Procesamiento de Datos"),
("Oficial de Contabilidad","Oficial de Contabilidad"),
("Coordinador de Contabilidad","Coordinador de Contabilidad"),
("Jefe de Grupo de Contabilidad","Jefe de Grupo de Contabilidad"),
("Especialista de Contabilidad","Especialista de Contabilidad"),
("Jefe de Oficina A","Jefe de Oficina A"),
("Jefe Tecnico de Cobranza y Adeudos","Jefe Tecnico de Cobranza y Adeudos"),
("Jefe de Grupo de Servicios de Personal","Jefe de Grupo de Servicios de Personal"),
("Camillero de Vehiculos de Servicios Ordinarios y Programados","Camillero de Vehiculos de Servicios Ordinarios y Programados"),
("Operador de Vehiculos de Servicios Ordinarios y Programados","Operador de Vehiculos de Servicios Ordinarios y Programados"),
("Operador de Ambulancias","Operador de Ambulancias"),
("Controlador de Vehiculos de Servicios Ordinarios y Programados","Controlador de Vehiculos de Servicios Ordinarios y Programados"), 
("Auxiliar de Velatorio","Auxiliar de Velatorio"),
("Operador de Velatorio","Operador de Velatorio"),
("Ayudante de Embalsamiento","Ayudante de Embalsamiento"),
("Veterinario","Veterinario"), 
("Yesista","Yesista"), ]

    matricula = forms.CharField(label='Matrícula', max_length=100, widget=forms.TextInput({'class': 'form-control'}))
    nombre = forms.CharField(label='Nombre Completo', max_length=250, widget=forms.TextInput({'class':'form-control'}))
    categoria = forms.ChoiceField(label='Categoría', widget=forms.Select(attrs={'class': 'form-control'}), choices=CATEGORIAS,)
    antiguedad = forms.CharField(label='Antiguedad', max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}))
    adscripcion = forms.ChoiceField(label='Unidad de Adscripción', widget=forms.Select(attrs={'class': 'form-control'}), choices=ADSCRIPCIONES,)
    t_contr = forms.ChoiceField(label='Tipo de Contratación', widget=forms.Select(attrs={'class': 'form-control'}), choices=T_CONTR,)
    turno = forms.ChoiceField(label='Turno', widget=forms.Select(attrs={'class': 'form-control'}), choices=TURNO,)
    email = forms.CharField(label='Email', max_length=150, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    domicilio = forms.CharField(label='Domicilio Particular', max_length=250, widget=forms.TextInput(attrs={'class': 'form-control'}))
    telefono =  forms.CharField(label='Teléfono', max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}))



class childForm(forms.Form):

    SEXO = [
        ('HOMBRE', 'HOMBRE'),
        ('MUJER', 'MUJER'),
    ]

    nombre = forms.CharField(label='Nombre Niño(a)', max_length=150, widget=forms.TextInput(attrs={'class': 'form-control'}))
    f_nac = forms.CharField(label='Fecha de Nacimiento', widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    edad = forms.CharField(label='Edad', max_length=30, widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)
    sexo = forms.ChoiceField(label='Sexo', widget=forms.Select(attrs={'class': 'form-control'}), choices=SEXO,)
    entregado = forms.CharField(label='Entregado', max_length=150, widget=forms.TextInput(attrs={'class': 'form-control'}), required=False)